### ISSUE TITLE
Add minimal example

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/ya2ro#34]
I would like an example where I can just fill in links from dois and github ids.
For example:
```
# Mandatory field
type: "paper"

title: "Work done in SOSEN"

datasets:
  - doi_dataset: https://doi.org/10.6084/m9.figshare.14916684.v1
  - doi_dataset: https://doi.org/10.5281/zenodo.5139550

software:
  - link: https://github.com/KnowledgeCaptureAndDiscovery/somef

bibliography:
  - DOI WHEN SUPPORTED
 
authors:
  # Alternative way if participant has an ORCID

  -
    orcid: http://orcid.org/0000-0003-0454-7145
    role: "Supervisor"

```
