### ISSUE TITLE
Fields are inconsistent

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/ya2ro#40]
Right now we have `doi` for datasets, `link` for software and nothing for papers. 

When we use the minimal version (which is the one I intend to use the most), I think it should be accepted to just have lists of links.

If you detect key-value pairs, then you know you have something a little more qualified.

**Comment by PavelAntonia** [comment]
Now this format is also supported:

```yaml
# Mandatory field
type: "paper"

title: "Work done in SOSEN"

datasets:
  - https://doi.org/10.6084/m9.figshare.14916684.v1
  - https://doi.org/10.5281/zenodo.5139550


software:
  - https://github.com/KnowledgeCaptureAndDiscovery/somef

bibliography:
  - https://doi.org/10.1109/BigData47090.2019.9006447
  
authors:
  # Alternative way if participant has an ORCID
  -
    orcid: http://orcid.org/0000-0003-0454-7145
    role: "Supervisor"
```
